# Generated by Django 2.1 on 2018-08-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20180830_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='groupAdmin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='groups.GroupAdmin'),
        ),
        migrations.AlterField(
            model_name='groupadmin',
            name='adminName',
            field=models.CharField(max_length=50),
        ),
    ]
