# Generated by Django 2.1 on 2018-08-30 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_remove_group_groupadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='GroupAdmin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupAdmin',
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ManyToManyField(to='groups.Category'),
        ),
    ]
