# Generated by Django 2.1 on 2018-08-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_profile_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groupName',
        ),
    ]
