# Generated by Django 2.1 on 2018-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_profile_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='groups.profile'),
        ),
    ]
