# Generated by Django 2.1 on 2018-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20180830_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='groups.profile'),
        ),
    ]
