# Generated by Django 2.1 on 2018-08-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_auto_20180831_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groupName',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
