# Generated by Django 2.0.5 on 2018-09-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_auto_20180908_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
