# Generated by Django 2.0.5 on 2018-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_remove_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ManyToManyField(related_name='groups', to='groups.Category'),
        ),
    ]
