# Generated by Django 2.0.5 on 2018-09-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_auto_20180908_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='catList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Category')),
                ('group', models.ManyToManyField(to='groups.Group')),
            ],
        ),
    ]
