# Generated by Django 2.0.5 on 2018-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_catlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='catlist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ManyToManyField(related_name='categorys', to='groups.Group'),
        ),
        migrations.DeleteModel(
            name='catList',
        ),
    ]
